"""Initial migration.

Revision ID: 6607409b446b
Revises: 
Create Date: 2022-12-14 02:56:54.556058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6607409b446b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s2_cell_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.String(), nullable=False),
    sa.Column('resolution_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'cell_id'),
    sa.UniqueConstraint('cell_id')
    )
    op.create_table('geo_ids',
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['s2_cell_tokens.cell_id'], ),
    sa.PrimaryKeyConstraint('geo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_ids')
    op.drop_table('s2_cell_tokens')
    # ### end Alembic commands ###
